version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: ls
  test:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: echo "this is the test job"
      - run: ls
  build-image:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: |
          docker build -t test . 
      - run: |
          echo $CIRCLE_SHA1
          echo $CIRCLE_PROJECT_REPONAME

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-image:
          requires:
            - test