version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: ubuntu:latest
        auth:
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: ls
  test:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: echo "this is the test job"
      - run: ls

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build