version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: ls
  test:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: echo "this is the test job"
      - run: ls
  build-image:
    environment:
      IMAGE_NAME: $CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
    docker:
      - image: docker:latest
        auth:
          username: dimarmen
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: |
          docker build -t dimarmen/test01 .
          docker push dimarmen/test01
      - run: |
          echo $CIRCLE_SHA1
          echo $CIRCLE_PROJECT_REPONAME
          echo $IMAGE_NAME


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-image:
          requires:
            - test