version: 2.1
orbs:
  slack: circleci/slack@4.1
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: ls
  test:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: echo "this is the test job"
      - run: ls
  build-image:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          command: |
            apk update
            apk install curl
      - run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          docker build -t $DOCKERHUB_USERNAME/test01:$CIRCLE_SHA1 .
          docker push $DOCKERHUB_USERNAME/test01:$CIRCLE_SHA1
          /usr/bin/apt update && /usr/bin/apt install curl
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-image:
          requires:
            - test